module.exports = {
  "_id": "63a3f7cbf03d9c618cf3582f",
  "agoraKey": "",
  "agoraCertificate": "",
  "privacyPolicyLink": "https://www.google.com/",
  "privacyPolicyText": " If you are 18 years old then you can use the App. We ask everyone on the app to Be kind and respectful, so every person can have a great experience. We evaluate Your Privacy and Personal information. If you want to use the App then you have to follow our Terms & Conditions and Privacy Policy.",
  "termAndCondition": "https://www.google.com/",
  "googlePlayEmail": "Google Play Email",
  "googlePlayKey": "",
  "googlePlaySwitch": true,
  "stripeSwitch": true,
  "stripePublishableKey": "",
  "stripeSecretKey": "",
  "isAppActive": true,
  "welcomeMessage": "welcome to app",
  "razorPayId": "",
  "razorPaySwitch": true,
  "razorSecretKey": "",
  "chargeForRandomCall": 100,
  "chargeForPrivateCall": 20,
  "coinPerDollar": 200,
  "coinCharge": 50,
  "paymentGateway": [
    "PayPal",
    "Banking",
    "Paytm"
  ],
  "withdrawLimit": 500,
  "link": "9428577490",
  "isFake": true,
  "privateKey": {
    "type": "service_account",
    "project_id": "",
    "private_key_id": "",
    "private_key": "-----BEGIN PRIVATE KEY-----\nblahblah\n-----END PRIVATE KEY-----\n",
    "client_email": "",
    "client_id": "",
    "auth_uri": "",
    "token_uri": "",
    "auth_provider_x509_cert_url": "",
    "client_x509_cert_url": "",
    "universe_domain": "googleapis.com"
  },
  "redirectAppUrl": "Here Redirect App URL",
  "redirectMessage": "Here Redirect Message",
  "flutterWaveId": "",
  "flutterWaveSwitch": false,
  "loginBonus": 30
};